[tool.poetry]
name = "ffps"
version = "0.1.0"
description = ""
authors = ["apar2021 <apar2021@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pymongo = "^4.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
